version: "3.8"

services:
  db:
    build:
      context: ./db-postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./db-postgres/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
